version: '3'

services:
  back:
    build: .
    volumes:
      - ".:/back"
      - my-datavolume:/back/src/database
    ports:
      - 3000:3000
    environment:
      - PORT=3000
volumes:
  my-datavolume: